### ISSUE TITLE
Add peer fails

### ISSUE THREAD

**Issue by bendonderer** [das-kaesebrot/wg-interactive#3]
When trying to add a peer the following error occurs:

```
Please select an operation to perform:
[a] Add peer
[l] List all peers and return to this menu
[d] Delete peer
> a
Selected operation: add

Traceback (most recent call last):
  File "wg-interactive.py", line 485, in <module>
    main()
  File "wg-interactive.py", line 479, in main
    if selectedOperation.get('short') == "add": addNewPeerToInterface(wc, selectedWGName, absWGPath, wgConfPath)
  File "wg-interactive.py", line 111, in addNewPeerToInterface
    if ipaddress.ip_address(addr.get('addr')).is_global:
  File "/usr/lib/python3.7/ipaddress.py", line 54, in ip_address
    address)
ValueError: 'fe80::dea6:32ff:fe47:9a11%eth0' does not appear to be an IPv4 or IPv6 address
```

**Comment by das-kaesebrot** [comment]
What's the output of `ip a` on your system?

**Comment by bendonderer** [comment]
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether dc:a6:32:47:9a:11 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.11/24 brd 192.168.1.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 fdee:569e:153:1:dea6:32ff:fe47:9a11/64 scope global dynamic mngtmpaddr noprefixroute
       valid_lft 9590sec preferred_lft 2390sec
    inet6 fe80::dea6:32ff:fe47:9a11/64 scope link
       valid_lft forever preferred_lft forever
3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether dc:a6:32:47:9a:12 brd ff:ff:ff:ff:ff:ff
4: wg0: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 10.0.0.1/24 scope global wg0
       valid_lft forever preferred_lft forever
```

**Comment by das-kaesebrot** [comment]
This seems to be a bug in the `netifaces` library. I'll try to work around it!

**Comment by das-kaesebrot** [comment]
32d9ce7 is a very hacky workaround, but that should do the job for now.
